name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  mascot: Mona
  HASURA_ADMIN_SECRET: 3MsvWqi2z0lZfsndBL3ruce6M2HaQEYp1rov5X60l32XwEEdJojh80BAM6nITcrg

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - run: npm install
      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out